import React, { JSX } from "react";
import { categories } from "./categories";
import { masterCategoriesArray } from "./masterCategories";

export type BlockCategory = {
  name: string
  title: string
  slug?: string
  metaTitle?: string
  metaDescription?: string
  metaKeywords?: string
}

export interface RegistryBlock {
  name: string;
  title: string;
  description: string;
  type?: string;
  categories: BlockCategory[];
  masterCategory: BlockCategory;
  dependencies?: string[];
  registryDependencies?: string[];
  component: React.LazyExoticComponent<() => JSX.Element>;
  files: { path: string; target?: string; type?: string }[];
  layout?: React.FC<{ children: React.ReactNode }>;
  isPro?: boolean;
  isDraft?: boolean;
  figmaLink?: string;
  created_at?: string;
  iframeHeight?: string | number;
}

const MasterCatWebsite = masterCategoriesArray[0];
const MasterCatAdmin = masterCategoriesArray[1];
const MasterCatEcommerce = masterCategoriesArray[2];

export const blocks: RegistryBlock[] = [
  {
    name: 'hero-01',
    title: 'Hero 01 - Agency Hero Section',
    description: 'Clean agency hero section designed for SaaS and startup websites, featuring bold headline, gradient background, trust badges, client logos, and high converting CTAs for lead generation.',
    type: "registry:block",
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=2262-8794&t=1YcME6jZvCdiVSmg-1",
    dependencies: ["@iconify/react", "motion"],
    registryDependencies: ["button", "sheet", "navigation-menu"],
    iframeHeight: "770px",
    files: [
      {
        path: 'src/components/shadcn-space/blocks/hero-01/page.tsx',
        type: "registry:page",
        target: 'app/hero-01/page.tsx',
      },
      {
        path: 'src/assets/logo/logo.tsx',
        type: "registry:component",
        target: 'assets/logo/logo.tsx',
      },
      {
        path: 'src/components/shadcn-space/blocks/hero-01/index.tsx',
        type: "registry:page",
        target: 'components/shadcn-space/blocks/hero-01/index.tsx',
      },
      {
        path: 'src/components/shadcn-space/blocks/hero-01/hero.tsx',
        type: "registry:component",
        target: 'components/shadcn-space/blocks/hero-01/hero.tsx',
      },
      {
        path: 'src/components/shadcn-space/blocks/hero-01/header.tsx',
        type: "registry:component",
        target: 'components/shadcn-space/blocks/hero-01/header.tsx',
      },
      {
        path: 'src/components/shadcn-space/blocks/hero-01/brand-slider.tsx',
        type: "registry:component",
        target: 'components/shadcn-space/blocks/hero-01/brand-slider.tsx',
      },
      {
        path: 'src/components/shadcn-space/animations/splash-cursor.jsx',
        type: "registry:component",
        target: 'components/shadcn-space/animations/splash-cursor.tsx',
      },
      {
        path: 'src/components/shadcn-space/animations/marquee.tsx',
        type: "registry:component",
        target: 'components/shadcn-space/animations/marquee.tsx',
      }
    ],
    component: React.lazy(
      () => import('@/components/shadcn-space/blocks/hero-01/page')
    ),
    created_at: '2025-12-09T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.hero],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'hero-02',
    title: 'Hero 02 - Real Estate Hero Section',
    description: 'Luxury real estate hero section crafted for property listings, featuring immersive imagery, location highlight, key amenities, pricing details, and prominent Schedule a tour CTA for faster inquiries.',
    type: "registry:block",
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=2262-9246&t=1YcME6jZvCdiVSmg-1",
    dependencies: ["lucide-react", "motion"],
    registryDependencies: ["sheet", "button", "separator"],
    files: [{
      path: 'src/components/shadcn-space/blocks/hero-02/page.tsx',
      type: "registry:page",
      target: 'app/hero-02/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/hero-02/hero.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/hero-02/hero.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/hero-02/seamless-cloud.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/hero-02/seamless-cloud.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/hero-02/navbar.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/hero-02/navbar.tsx',
    },
    {
      path: 'src/components/shadcn-space/animations/marquee.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/animations/marquee.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/hero-02/index.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/hero-02/index.tsx',
    }],
    component: React.lazy(
      () => import('@/components/shadcn-space/blocks/hero-02/page')
    ),
    created_at: '2025-12-09T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.hero],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'hero-03',
    title: 'Hero 03 - Digital Agency Hero Section',
    description: 'High-impact digital agency hero section with cinematic background video, bold typography, brand driven headline, and clear CTA, perfect for creative studios and performance-focused marketing websites.',
    type: "registry:block",
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=2262-9928&t=1YcME6jZvCdiVSmg-1",
    dependencies: ["lucide-react", "motion"],
    registryDependencies: [
      "dropdown-menu",
    ],
    files: [{
      path: 'src/components/shadcn-space/blocks/hero-03/page.tsx',
      type: "registry:page",
      target: 'app/hero-03/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/hero-03/hero.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/hero-03/hero.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/hero-03/navbar.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/hero-03/navbar.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/hero-03/navlink.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/hero-03/navlink.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/hero-03/index.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/hero-03/index.tsx',
    },
    ],
    component: React.lazy(
      () => import('@/components/shadcn-space/blocks/hero-03/page')
    ),
    created_at: '2025-12-09T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.hero],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'feature-01',
    title: 'Feature 01 - Feature with Testimonials',
    description: 'A trust focused feature section combining a highlighted customer testimonial with supporting benefit cards, perfect for product or SaaS pages to showcase social proof and reinforce key advantages.',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=2577-3409&t=1YcME6jZvCdiVSmg-1",
    type: "registry:block",
    dependencies: ["lucide-react"],
    iframeHeight: "800px",
    registryDependencies: [
      "card",
      "avatar"
    ],
    files: [{
      path: 'src/components/shadcn-space/blocks/feature-01/page.tsx',
      type: "registry:page",
      target: 'app/feature-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/feature-01/index.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/feature-01/index.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/feature-01/feature.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/feature-01/feature.tsx',
    },
    ],
    component: React.lazy(() => import('@/components/shadcn-space/blocks/feature-01/page.tsx')),
    created_at: '2026-01-06T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.feature],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'feature-02',
    title: 'Feature 02 - Three Columns Feature with Icons',
    description: 'A clean three card feature grid with icons and concise copy, built for product or SaaS pages to communicate core benefits clearly while maintaining a developer friendly, scalable layout.',
    type: "registry:block",
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=2570-1748&t=1YcME6jZvCdiVSmg-1",
    dependencies: ["lucide-react", "motion"],
    iframeHeight: "750px",
    registryDependencies: [
      "card",
      "badge",
      "button",
    ],
    files: [{
      path: 'src/components/shadcn-space/blocks/feature-02/page.tsx',
      type: "registry:page",
      target: 'app/feature-02/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/feature-02/index.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/feature-02/index.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/feature-02/feature.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/feature-02/feature.tsx',
    },
    ],
    component: React.lazy(() => import('@/components/shadcn-space/blocks/feature-02/page.tsx')),
    created_at: '2026-01-06T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.feature],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'about-us-section-01',
    title: 'About Us 01 - Impact Metrics',
    description: 'A bold about us section combining value pillars, headline messaging, and performance counters, perfect for agencies or studios to highlight expertise, achievements, and credibility at a glance.',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=2652-2629&t=1YcME6jZvCdiVSmg-1",
    type: "registry:block",
    dependencies: ["lucide-react"],
    registryDependencies: [],
    files: [{
      path: 'src/components/shadcn-space/blocks/about-us-01/page.tsx',
      type: "registry:page",
      target: 'app/about-us-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/about-us-01/index.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/about-us-01/index.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/about-us-01/about-us.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/about-us-01/about-us.tsx',
    },
    ],
    component: React.lazy(() => import('@/components/shadcn-space/blocks/about-us-01/page')),
    created_at: '2026-01-06T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.aboutus],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'pricing-01',
    title: 'Pricing 01 - Startup Pricing Plans',
    description: 'A clean two tier pricing section with feature comparison, highlighted plans, and strong CTAs, suited for agencies, Startups & SaaS to convert visitors by clearly presenting value and monthly subscription options.',
    type: "registry:block",
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=2547-18349&t=1YcME6jZvCdiVSmg-1",
    dependencies: ["lucide-react", "motion"],
    registryDependencies: [
      "card",
      "badge",
      "separator",
      "button"
    ],
    files: [{
      path: 'src/components/shadcn-space/blocks/pricing-01/page.tsx',
      type: "registry:page",
      target: 'app/pricing-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/pricing-01/pricing.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/pricing-01/pricing.tsx',
    },
    ],
    component: React.lazy(
      () => import('@/components/shadcn-space/blocks/pricing-01/page')
    ),
    created_at: '2026-01-06T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.pricing],
    masterCategory: MasterCatWebsite,
  },
  {
    name: "pricing-02",
    title: "Pricing 02 - Scalable Pricing Table",
    description:
      "A three tier pricing layout with a highlighted recommended plan, feature checklists, and clear CTAs, perfect for any website having pricing section to guide users toward the most valuable subscription option.",
    type: "registry:block",
    dependencies: ["lucide-react", "motion"],
    registryDependencies: ["card", "badge", "separator", "button"],
    iframeHeight: "948px",
    files: [
      {
        path: "src/components/shadcn-space/blocks/pricing-02/page.tsx",
        type: "registry:page",
        target: "app/pricing-02/page.tsx",
      },
      {
        path: "src/components/shadcn-space/blocks/pricing-02/pricing.tsx",
        type: "registry:component",
        target: "components/shadcn-space/blocks/pricing-02/pricing.tsx",
      },
    ],
    component: React.lazy(
      () => import("@/components/shadcn-space/blocks/pricing-02/page")
    ),
    created_at: "2026-01-07T17:42:25+05:30",
    isPro: false,
    isDraft: false,
    categories: [categories.pricing],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'testimonial-01',
    title: 'Testimonial 01 - Bentro Grid Testimonials',
    description: 'A multi card testimonial section combining customer quotes, imagery, and performance stats, ideal for showcasing social proof, building trust, and reinforcing brand credibility across product or agency websites.',
    type: "registry:block",
    dependencies: ["motion"],
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=3024-8207&t=1YcME6jZvCdiVSmg-1",
    registryDependencies: [
      "card",
      "badge",
    ],
    iframeHeight: "1202px",
    files: [{
      path: 'src/components/shadcn-space/blocks/testimonial-01/page.tsx',
      type: "registry:page",
      target: 'app/testimonial-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/testimonial-01/testimonial.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/testimonial-01/testimonial.tsx',
    },
    ],
    component: React.lazy(
      () => import('@/components/shadcn-space/blocks/testimonial-01/page')
    ),
    created_at: '2026-01-08T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.testimonials],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'testimonial-02',
    title: 'Testimonial 02 - Testimonial Slider Showcase',
    description: 'A clean testimonial slider with customer photo, detailed quote, navigation controls, and partner logos—perfect for highlighting success stories and building instant trust on landing pages.',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=2652-2639&t=1YcME6jZvCdiVSmg-1",
    type: "registry:block",
    dependencies: ["@iconify/react", "motion"],
    registryDependencies: [
      "badge",
      "carousel"
    ],
    files: [{
      path: 'src/components/shadcn-space/blocks/testimonial-02/page.tsx',
      type: "registry:page",
      target: 'app/testimonial-02/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/testimonial-02/testimonial.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/testimonial-02/testimonial.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/testimonial-02/index.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/testimonial-02/index.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/testimonial-02/brand-slider.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/testimonial-02/brand-slider.tsx',
    },
    {
      path: 'src/components/shadcn-space/animations/marquee.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/animations/marquee.tsx',
    }],
    iframeHeight: "800px",
    component: React.lazy(() => import('@/components/shadcn-space/blocks/testimonial-02/page')),
    created_at: '2026-01-08T18:53:10+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.testimonials],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'portfolio-01',
    title: 'Portfolio 01 - Clean Portfolio Grid',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=2671-616&t=s6w7yYhqg5U0ajyZ-1",
    description: 'A modern portfolio section displaying featured projects with tags, visuals, and categories, ideal for agencies or freelancers to showcase real-world transformations, expertise, and design impact.',
    type: "registry:block",
    dependencies: ["motion"],
    registryDependencies: [
      "card",
      "badge",
    ],
    iframeHeight: "1280px",
    files: [{
      path: 'src/components/shadcn-space/blocks/portfolio-01/page.tsx',
      type: "registry:page",
      target: 'app/portfolio-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/portfolio-01/portfolio.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/portfolio-01/portfolio.tsx',
    },
    ],
    component: React.lazy(
      () => import('@/components/shadcn-space/blocks/portfolio-01/page')
    ),
    created_at: '2026-01-09T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.portfolio],
    masterCategory: MasterCatWebsite,
  },
  {
    name: "team-01",
    title: "Team 01 - Creative Team Showcase",
    description:
      "A vibrant team section featuring profile cards with roles and social links, perfect for agencies or startups to humanize their brand, highlight talent, and build authentic connections.",
    type: "registry:block",
    dependencies: ["lucide-react"],
    registryDependencies: ["badge"],
    iframeHeight: "800px",
    files: [
      {
        path: "src/components/shadcn-space/blocks/team-01/page.tsx",
        type: "registry:page",
        target: "app/team-01/page.tsx",
      },
      {
        path: "src/components/shadcn-space/blocks/team-01/team.tsx",
        type: "registry:component",
        target: "components/shadcn-space/blocks/team-01/team.tsx",
      },
    ],
    component: React.lazy(
      () => import("@/components/shadcn-space/blocks/team-01/page.tsx")
    ),
    created_at: "2026-01-06T17:42:25+05:30",
    isPro: false,
    isDraft: false,
    categories: [categories.team],
    masterCategory: MasterCatWebsite,
  },
  {
    name: "team-02",
    title: "Team 02 - Modern Team Grid",
    description:
      "A clean team grid with large profile cards, roles, and social icons, ideal for agencies or SaaS companies to introduce key members and strengthen brand authenticity.",
    type: "registry:block",
    dependencies: ["lucide-react"],
    registryDependencies: ["badge"],
    iframeHeight: "800px",
    files: [
      {
        path: "src/components/shadcn-space/blocks/team-02/page.tsx",
        type: "registry:page",
        target: "app/team-02/page.tsx",
      },
      {
        path: "src/components/shadcn-space/blocks/team-02/team.tsx",
        type: "registry:component",
        target: "components/shadcn-space/blocks/team-02/team.tsx",
      },
    ],
    component: React.lazy(
      () => import("@/components/shadcn-space/blocks/team-02/page.tsx")
    ),
    created_at: "2026-01-06T17:42:25+05:30",
    isPro: false,
    isDraft: false,
    categories: [categories.team],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'cta-01',
    title: 'CTA 01 - Gradient Call-to-Action Banner',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=2683-1804&t=s6w7yYhqg5U0ajyZ-1",
    description: 'A minimal full width CTA section with soft gradient background, persuasive headline, and primary action button, perfect for converting visitors into leads at the end of any page.',
    type: "registry:block",
    dependencies: ["@iconify/react", "motion"],
    registryDependencies: ["button"],
    files: [{
      path: 'src/components/shadcn-space/blocks/cta-01/page.tsx',
      type: "registry:page",
      target: 'app/cta-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/cta-01/cta.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/cta-01/cta.tsx',
    }],
    iframeHeight: "550px",
    component: React.lazy(() => import('@/components/shadcn-space/blocks/cta-01/page')),
    created_at: '2026-01-09T18:53:10+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.cta],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'cta-02',
    title: 'CTA 02 - Video Background CTA',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=2683-1856&t=s6w7yYhqg5U0ajyZ-1",
    description: 'A high impact call-to-action section with autoplay background video, bold overlay headline, primary button, and rotating ticker text, perfect for luxury brands or real estate to capture attention instantly.',
    type: "registry:block",
    dependencies: ["@iconify/react"],
    registryDependencies: ["separator"],
    files: [{
      path: 'src/components/shadcn-space/blocks/cta-02/page.tsx',
      type: "registry:page",
      target: 'app/cta-02/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/cta-02/cta.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/cta-02/cta.tsx',
    },
    {
      path: 'src/components/shadcn-space/animations/marquee.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/animations/marquee.tsx',
    }],
    iframeHeight: "620px",
    component: React.lazy(() => import('@/components/shadcn-space/blocks/cta-02/page')),
    created_at: '2026-01-09T18:53:10+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.cta],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'services-01',
    title: 'Services 01 - Creative Services Overview',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=2683-2124&t=s6w7yYhqg5U0ajyZ-1",
    description: 'A colorful services section with icon cards and dual CTAs, perfect for agencies to present core offerings, guide visitors to portfolios, and drive collaboration with clear next steps.',
    type: "registry:block",
    dependencies: ["lucide-react", "motion"],
    registryDependencies: [
      "card",
      "badge",
      "button",
    ],
    files: [{
      path: 'src/components/shadcn-space/blocks/services-01/page.tsx',
      type: "registry:page",
      target: 'app/services-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/services-01/services.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/services-01/services.tsx',
    },
    ],
    component: React.lazy(
      () => import('@/components/shadcn-space/blocks/services-01/page')
    ),
    created_at: '2026-01-09T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.services],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'services-02',
    title: 'Services 02 - Services Animated Block',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=2683-2562&t=s6w7yYhqg5U0ajyZ-1",
    description: 'A premium dark mode services section with interactive list, visual preview, and detailed descriptions, ideal for creative agencies to showcase capabilities while maintaining a bold, modern brand presence.',
    type: "registry:block",
    dependencies: ["@iconify/react"],
    registryDependencies: ["badge", "button"],
    files: [{
      path: 'src/components/shadcn-space/blocks/services-02/page.tsx',
      type: "registry:page",
      target: 'app/services-02/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/services-02/services.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/services-02/services.tsx',
    }],
    iframeHeight: "950px",
    component: React.lazy(() => import('@/components/shadcn-space/blocks/services-02/page')),
    created_at: '2026-01-10T18:53:10+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.services],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'faq-01',
    title: 'FAQ 01 - Expandable FAQ Section',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=2683-2701&t=s6w7yYhqg5U0ajyZ-1",
    description: 'A clean accordion style FAQ section with expandable answers, ideal for agencies or SaaS sites to address common questions, reduce friction, and improve user confidence before conversion.',
    type: "registry:block",
    dependencies: ["@iconify/react"],
    registryDependencies: ["badge", "accordion"],
    files: [{
      path: 'src/components/shadcn-space/blocks/faq-01/page.tsx',
      type: "registry:page",
      target: 'app/faq-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/faq-01/faq.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/faq-01/faq.tsx',
    }],
    iframeHeight: "900px",
    component: React.lazy(() => import('@/components/shadcn-space/blocks/faq-01/page')),
    created_at: '2026-01-09T18:53:10+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.Faqs],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'newsletter-01',
    title: 'Newsletter 01 - Newsletter Subscription CTA',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=2683-2897&t=s6w7yYhqg5U0ajyZ-1",
    description: 'A minimal newsletter signup section with bold headline, social-proof subtext, and inline email form, ideal for capturing leads and growing your audience with a frictionless experience.',
    type: "registry:block",
    dependencies: ["@iconify/react"],
    registryDependencies: ["input-group"],
    files: [{
      path: 'src/components/shadcn-space/blocks/newsletter-01/page.tsx',
      type: "registry:page",
      target: 'app/newsletter-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/newsletter-01/newsletter.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/newsletter-01/newsletter.tsx',
    }],
    iframeHeight: "578px",
    component: React.lazy(() => import('@/components/shadcn-space/blocks/newsletter-01/page')),
    created_at: '2026-01-10T18:53:10+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.newsletter],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'blog-01',
    title: 'Blog 01 - Latest Blog & News Grid',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=3678-1278&t=s6w7yYhqg5U0ajyZ-1",
    description: 'A modern blog section with featured posts, large thumbnails, publish dates, and headlines, ideal for sharing agency updates, design insights, and thought leadership to keep visitors engaged.',
    type: "registry:block",
    dependencies: ["motion"],
    registryDependencies: [
      "card",
      "badge",
    ],
    iframeHeight: "820px",
    files: [{
      path: 'src/components/shadcn-space/blocks/blog-01/page.tsx',
      type: "registry:page",
      target: 'app/blog-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/blog-01/blog.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/blog-01/blog.tsx',
    },
    ],
    component: React.lazy(
      () => import('@/components/shadcn-space/blocks/blog-01/page')
    ),
    created_at: '2026-01-10T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.blog],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'contact-01',
    title: 'Contact 01 - Project Inquiry Contact Form',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=3678-5036&t=s6w7yYhqg5U0ajyZ-1",
    description: 'A conversion focused contact section with project inquiry form, contact details, and trust badges, ideal for agencies or freelancers to capture qualified leads and start meaningful client conversations.',
    type: "registry:block",
    dependencies: [""],
    registryDependencies: [
      "card",
      "button",
      "input",
      "textarea",
      "checkbox",
      "label",
      "select",
      "separator",
    ],
    files: [{
      path: 'src/components/shadcn-space/blocks/contact-01/page.tsx',
      type: "registry:page",
      target: 'app/contact-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/contact-01/index.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/contact-01/index.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/contact-01/contact-info.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/contact-01/contact-info.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/contact-01/contact-form.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/contact-01/contact-form.tsx',
    },
    {
      path: 'src/components/shadcn-space/animations/marquee.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/animations/marquee.tsx',
    },
    ],
    component: React.lazy(() => import('@/components/shadcn-space/blocks/contact-01/page.tsx')),
    created_at: '2026-01-09T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.contact],
    masterCategory: MasterCatWebsite,
  },
  {
    name: "navbar-01",
    title: "Navbar 01 - Minimal Agency Navbar",
    description:
      "A clean top navigation bar with logo, page links, and standout CTA button, ideal for agency or SaaS websites to guide users and drive collaboration effortlessly.",
    type: "registry:block",
    dependencies: ["@iconify/react"],
    registryDependencies: ["button", "dropdown-menu", "navigation-menu"],
    iframeHeight: "300px",
    files: [
      {
        path: "src/components/shadcn-space/blocks/navbar-01/page.tsx",
        type: "registry:page",
        target: "app/navbar-01/page.tsx",
      },
      {
        path: "src/components/shadcn-space/blocks/navbar-01/navbar.tsx",
        type: "registry:component",
        target: "components/shadcn-space/blocks/navbar-01/navbar.tsx",
      },
    ],
    component: React.lazy(
      () => import("@/components/shadcn-space/blocks/navbar-01/page.tsx")
    ),
    created_at: "2026-01-06T17:42:25+05:30",
    isPro: false,
    isDraft: false,
    categories: [categories.navbar],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'footer-01',
    title: 'Footer 01 - Agency Footer Layout',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=2683-5671&t=s6w7yYhqg5U0ajyZ-1",
    description: 'A clean multi column footer with brand summary, sitemap links, legal pages, contact details, and social icons, perfect for agencies to provide clarity, trust, and easy navigation.',
    type: "registry:block",
    dependencies: ["lucide-react"],
    registryDependencies: [
      "separator",
    ],
    iframeHeight: "516px",
    files: [{
      path: 'src/components/shadcn-space/blocks/footer-01/page.tsx',
      type: "registry:page",
      target: 'app/footer-01/page.tsx',
    },
    {
      path: 'src/assets/logo/logo.tsx',
      type: "registry:component",
      target: 'assets/logo/logo.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/footer-01/footer.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/footer-01/footer.tsx',
    },
    ],
    component: React.lazy(
      () => import('@/components/shadcn-space/blocks/footer-01/page')
    ),
    created_at: '2026-01-10T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.footer],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'footer-02',
    title: 'Footer 02 - Dark Conversion Footer',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=3678-5041&t=s6w7yYhqg5U0ajyZ-1",
    description: 'A bold dark themed footer with newsletter signup, strong contact CTA, navigation links, and legal pages, ideal for real estate or SaaS websites to drive engagement at the page end.',
    type: "registry:block",
    dependencies: [],
    registryDependencies: ["button", "input", "separator"],
    files: [{
      path: 'src/components/shadcn-space/blocks/footer-02/page.tsx',
      type: "registry:page",
      target: 'app/footer-02/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/footer-02/footer.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/footer-02/footer.tsx',
    }],
    iframeHeight: "656px",
    component: React.lazy(() => import('@/components/shadcn-space/blocks/footer-02/page')),
    created_at: '2026-01-10T18:53:10+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.footer],
    masterCategory: MasterCatWebsite,
  },
  {
    name: "sidebar-01",
    title: "Sidebar 01 - Admin Dashboard Sidebar",
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=3678-4995&t=s6w7yYhqg5U0ajyZ-1",
    description:
      "A collapsible sidebar navigation with grouped menus, icons, and upgrade CTA, perfect for admin dashboards to organize pages, widgets, and apps while keeping workflows fast and intuitive.",
    type: "registry:block",
    dependencies: ["lucide-react"],
    registryDependencies: ["sidebar", "scroll-area", "collapsible", "card", "button"],
    files: [
      {
        path: "src/components/shadcn-space/blocks/sidebar-01/page.tsx",
        type: "registry:page",
        target: "app/sidebar-01/page.tsx",
      },
      {
        path: "src/assets/logo/logo.tsx",
        type: "registry:component",
        target: "assets/logo/logo.tsx",
      },
      {
        path: "src/components/shadcn-space/blocks/sidebar-01/nav-main.tsx",
        type: "registry:component",
        target: "components/shadcn-space/blocks/sidebar-01/nav-main.tsx",
      },
    ],
    component: React.lazy(
      () => import("@/components/shadcn-space/blocks/sidebar-01/page")
    ),
    created_at: "2026-01-15T18:53:10+05:30",
    isPro: false,
    isDraft: false,
    categories: [categories.sidebars],
    masterCategory: MasterCatAdmin,
  },
  {
    name: 'statistics-01',
    title: 'Statistics 01 - KPI Summary Cards',
    description: 'A compact statistics section with KPI cards highlighting earnings, expenses, weekly sales, and orders, ideal for admin dashboards to surface key business metrics at a glance.',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=3678-4897&t=s6w7yYhqg5U0ajyZ-1",
    type: "registry:block",
    dependencies: ["lucide-react"],
    registryDependencies: ["badge", "button", "card", "separator"],
    files: [
      {
        path: 'src/components/shadcn-space/blocks/statistics-01/page.tsx',
        type: "registry:page",
        target: 'app/statistics-01/page.tsx',
      },
      {
        path: 'src/components/shadcn-space/blocks/statistics-01/statistics.tsx',
        type: "registry:component",
        target: 'components/shadcn-space/blocks/statistics-01/statistics.tsx',
      },
    ],
    component: React.lazy(
      () =>
        import('@/components/shadcn-space/blocks/statistics-01/page')
    ),
    created_at: '2026-01-12T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.statistics],
    masterCategory: MasterCatAdmin,
  },
  {
    name: 'statistics-02',
    title: 'Statistics 02 - Business Metrics Bar',
    description: 'A horizontal KPI bar displaying orders, sales, profit, and expenses with weekly change indicators, ideal for dashboards to monitor short-term performance and trends at a glance.',
    type: "registry:block",
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=3678-4896&t=s6w7yYhqg5U0ajyZ-1",
    dependencies: ["@iconify/react"],
    registryDependencies: ["card", "badge"],
    files: [
      {
        path: 'src/components/shadcn-space/blocks/statistics-02/page.tsx',
        type: "registry:page",
        target: 'app/statistics-02/page.tsx',
      },
      {
        path: 'src/components/shadcn-space/blocks/statistics-02/statistics.tsx',
        type: "registry:component",
        target: 'components/shadcn-space/blocks/statistics-02/statistics.tsx'
      },
    ],
    component: React.lazy(
      () =>
        import('@/components/shadcn-space/blocks/statistics-02/page')
    ),
    created_at: '2026-01-12T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.statistics],
    masterCategory: MasterCatAdmin,
  },
  {
    name: 'chart-01',
    title: 'Chart 01 - Sales Performance Bar Chart',
    description: 'An interactive stacked bar chart displaying monthly earnings, profit, and expenses, ideal for admin dashboards to visualize financial trends, track growth, and support data-driven business decisions.',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=3380-11076&t=s6w7yYhqg5U0ajyZ-1",
    type: "registry:block",
    dependencies: ["recharts"],
    registryDependencies: ["card", "chart", "badge"],
    files: [{
      path: 'src/components/shadcn-space/blocks/chart-01/page.tsx',
      type: "registry:page",
      target: 'app/chart-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/chart-01/chart.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/chart-01/chart.tsx',
    }],
    component: React.lazy(
      () =>
        import('@/components/shadcn-space/blocks/chart-01/page')
    ),
    created_at: '2026-01-12T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.charts],
    masterCategory: MasterCatAdmin,
  },
  {
    name: 'chart-02',
    title: 'Chart 02 - Earnings Pie Chart',
    description: 'A clean donut chart widget summarizing total earnings with source-wise breakdown, perfect for admin dashboards to compare revenue streams, monitor growth, and highlight performance insights.',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=3678-4895&t=s6w7yYhqg5U0ajyZ-1",
    type: "registry:block",
    dependencies: ["recharts"],
    registryDependencies: ["card", "chart", "badge"],
    files: [{
      path: 'src/components/shadcn-space/blocks/chart-02/page.tsx',
      type: "registry:page",
      target: 'app/chart-02/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/chart-02/chart.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/chart-02/chart.tsx',
    }],
    component: React.lazy(
      () =>
        import('@/components/shadcn-space/blocks/chart-02/page')
    ),
    created_at: '2026-01-12T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.charts],
    masterCategory: MasterCatAdmin,
  },
  {
    name: 'chart-03',
    title: 'Chart 03 - Yearly Sales Comparison',
    description: 'A smooth line chart comparing this year versus last year sales with summary stats, ideal for dashboards to visualize performance trends and identify seasonal growth patterns quickly.',
    type: "registry:block",
    dependencies: ["lucide-react", "recharts"],
    registryDependencies: ["card", "chart", "badge"],
    files: [{
      path: 'src/components/shadcn-space/blocks/chart-03/page.tsx',
      type: "registry:page",
      target: 'app/chart-03/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/chart-03/chart.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/chart-03/chart.tsx',
    }],
    component: React.lazy(
      () =>
        import('@/components/shadcn-space/blocks/chart-03/page')
    ),
    created_at: '2026-01-12T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.charts],
    masterCategory: MasterCatAdmin,
  },

  {
    name: 'charts-04',
    title: 'Chart 04 - Weekly Sales',
    description: 'A compact bar chart widget showing daily sales for the past week with trend indicator, perfect for dashboards to highlight short-term performance and spot high-activity days instantly.',
    type: "registry:block",
    dependencies: ["lucide-react", "recharts"],
    registryDependencies: ["card", "badge", "dropdown-menu"],
    files: [{
      path: 'src/components/shadcn-space/blocks/chart-04/page.tsx',
      type: "registry:page",
      target: 'app/chart-04/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/chart-04/chart.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/chart-04/chart.tsx',
    }],
    component: React.lazy(
      () =>
        import('@/components/shadcn-space/blocks/chart-04/page')
    ),
    created_at: '2026-01-12T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.charts],
    masterCategory: MasterCatAdmin,
  },
  {
    name: 'bentogrid-01',
    title: 'Bento Grid 01 - Bento Grid Section',
    description: 'A visually rich bento grid that brings the world closer—highlighting stunning locations, cultural moments, and unforgettable experiences in a dynamic, bite-sized layout.',
    type: "registry:block",
    dependencies: ["motion", "lucide-react"],
    registryDependencies: [],
    iframeHeight: "1240px",
    files: [{
      path: 'src/components/shadcn-space/blocks/bento-grid-01/page.tsx',
      type: "registry:page",
      target: 'app/bento-grid-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/bento-grid-01/bentogrid.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/bento-grid-01/bentogrid.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/bento-grid-01/AnimatedUiBlock.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/bento-grid-01/AnimatedUiBlock.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/bento-grid-01/ReminderAnimation.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/bento-grid-01/ReminderAnimation.tsx',
    },
    ],
    component: React.lazy(() => import('@/components/shadcn-space/blocks/bento-grid-01/page')),
    created_at: '2026-01-20T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.bentogrid],
    masterCategory: MasterCatWebsite,
  },
  {
    name: "dashboard-shell-01",
    title: "Dashboard Shell 01",
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=4119-1651&t=s6w7yYhqg5U0ajyZ-1",
    description: "A modern dashboard shell with a sidebar and header, ideal for admin dashboards to organize and navigate through different sections.",
    type: "registry:block",
    dependencies: ["lucide-react", "recharts", "motion"],
    registryDependencies: ["sidebar", "scroll-area", "card", "button", "badge", "chart", "collapsible", "dropdown-menu", "separator", "checkbox", "progress", "table"],
    files: [{
      path: 'src/components/shadcn-space/blocks/dashboard-shell-01/page.tsx',
      type: "registry:page",
      target: 'app/dashboard-shell-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/dashboard-shell-01/salesbycountrywidget.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/dashboard-shell-01/salesbycountrywidget.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/dashboard-shell-01/site-header.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/dashboard-shell-01/site-header.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/dashboard-shell-01/top-product-table.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/dashboard-shell-01/top-product-table.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/dashboard-shell-01/statistics.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/dashboard-shell-01/statistics.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/dashboard-shell-01/sales-overview-chart.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/dashboard-shell-01/sales-overview-chart.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/dashboard-shell-01/nav-main.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/dashboard-shell-01/nav-main.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/dashboard-shell-01/earning-report-chart.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/dashboard-shell-01/earning-report-chart.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/dashboard-shell-01/app-sidebar.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/dashboard-shell-01/app-sidebar.tsx',
    },
    ],
    iframeHeight: "656px",
    component: React.lazy(() => import('@/components/shadcn-space/blocks/dashboard-shell-01/page')),
    created_at: '2026-01-10T18:53:10+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.dashboardShell],
    masterCategory: MasterCatAdmin,
  },
  {
    name: 'dialog-01',
    title: 'Dialog 01 - Newsletter Subscription Dialog',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=3678-6027&t=s6w7yYhqg5U0ajyZ-1",
    description: 'A modern modal popup for capturing newsletter signups with a friendly hero image, email field, opt-out checkbox, and clear call-to-action to boost conversions.',
    type: "registry:block",
    dependencies: [""],
    registryDependencies: [
      "dialog",
      "button",
      "input",
      "field",
      "checkbox"
    ],
    iframeHeight: "600px",
    files: [{
      path: 'src/components/shadcn-space/blocks/dialog-01/page.tsx',
      type: "registry:page",
      target: 'app/dialog-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/dialog-01/dialog.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/dialog-01/dialog.tsx',
    },

    ],
    component: React.lazy(() => import('@/components/shadcn-space/blocks/dialog-01/page')),
    created_at: '2026-01-15T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.dialog],
    masterCategory: MasterCatAdmin,
  },
  {
    name: 'dropdown-01',
    title: 'Dropdown 01 - User Account Dropdown',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=3678-6033&t=s6w7yYhqg5U0ajyZ-1",
    description: 'A compact user profile dropdown with quick access to subscriptions, invoices, account settings, and secure sign out, designed to improve navigation within modern SaaS dashboards.',
    type: "registry:block",
    dependencies: ["lucide-react"],
    registryDependencies: [
      "avatar",
      "dropdown-menu",
    ],
    iframeHeight: "500px",
    files: [{
      path: 'src/components/shadcn-space/blocks/dropdown-01/page.tsx',
      type: "registry:page",
      target: 'app/dropdown-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/dropdown-01/dropdown.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/dropdown-01/dropdown.tsx',
    },
    ],
    component: React.lazy(() => import('@/components/shadcn-space/blocks/dropdown-01/page')),
    created_at: '2026-01-15T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.dropdown],
    masterCategory: MasterCatAdmin,
  },
  {
    name: 'dropdown-02',
    title: 'Dropdown 02 - Notifications Dropdown',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=3678-6034&t=s6w7yYhqg5U0ajyZ-1",
    description: 'A real-time notifications dropdown displaying upcoming events, meetings, and reminders with timestamps and unread count—keeping users informed without leaving their workflow.',
    type: "registry:block",
    dependencies: ["lucide-react"],
    registryDependencies: [
      "button",
      "badge",
      "dropdown-menu",
    ],
    iframeHeight: "550px",
    files: [{
      path: 'src/components/shadcn-space/blocks/dropdown-02/page.tsx',
      type: "registry:page",
      target: 'app/dropdown-02/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/dropdown-02/dropdown.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/dropdown-02/dropdown.tsx',
    },
    ],
    component: React.lazy(() => import('@/components/shadcn-space/blocks/dropdown-02/page')),
    created_at: '2026-01-15T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.dropdown],
    masterCategory: MasterCatAdmin,
  },
  {
    name: 'forgot-password-01',
    title: 'Forgot Password 01 - Forgot Your Password Page',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=3678-6013&t=s6w7yYhqg5U0ajyZ-1",
    description: 'A minimal password recovery page that lets users request a secure reset link via email, helping reduce friction and support issues in authentication flows.',
    type: "registry:block",
    dependencies: [""],
    registryDependencies: [
      "button",
      "card",
      "input",
      "field",
    ],
    files: [{
      path: 'src/components/shadcn-space/blocks/forgot-password-01/page.tsx',
      type: "registry:page",
      target: 'app/forgot-password-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/forgot-password-01/forgot-password.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/forgot-password-01/forgot-password.tsx',
    },
    ],
    component: React.lazy(() => import('@/components/shadcn-space/blocks/forgot-password-01/page')),
    created_at: '2026-01-15T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.forgotPassword],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'forms-01',
    title: 'Forms 01 - Edit Profile Form',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=3678-6032&t=s6w7yYhqg5U0ajyZ-1",
    description: 'A user-friendly profile editing form with avatar upload, personal details, privacy controls, and action toggles, perfect for managing account information inside modern SaaS dashboards.',
    type: "registry:block",
    dependencies: [],
    registryDependencies: [
      "card",
      "button",
      "input",
      "field",
      "switch",
      "label"
    ],
    iframeHeight: "800px",
    files: [{
      path: 'src/components/shadcn-space/blocks/forms-01/page.tsx',
      type: "registry:page",
      target: 'app/forms-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/forms-01/profile-form.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/forms-01/profile-form.tsx',
    },
    ],
    component: React.lazy(() => import('@/components/shadcn-space/blocks/forms-01/page')),
    created_at: '2026-01-16T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.forms],
    masterCategory: MasterCatAdmin,
  },
  {
    name: 'gallery-01',
    title: 'Gallery 01 - Image Gallery Section',
    description: 'Explore a curated collection of breathtaking destinations and unforgettable experiences from around the world.',
    type: "registry:block",
    dependencies: [],
    registryDependencies: ["card"],
    iframeHeight: "900px",
    files: [{
      path: 'src/components/shadcn-space/blocks/gallery-01/page.tsx',
      type: "registry:page",
      target: 'app/gallery-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/gallery-01/gallery.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/gallery-01/gallery.tsx',
    },
    ],
    component: React.lazy(() => import('@/components/shadcn-space/blocks/gallery-01/page')),
    created_at: '2026-01-20T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.gallery],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'login-01',
    title: 'Login 01 - Developer-Friendly Login Page',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=3678-6003&t=s6w7yYhqg5U0ajyZ-1",
    description: 'A clean, secure login page with Google and GitHub authentication, remember-me support, and password recovery, built for modern SaaS products using shadcn UI.',
    type: "registry:block",
    dependencies: [""],
    registryDependencies: [
      "card",
      "button",
      "input",
      "checkbox",
      "field"
    ],
    iframeHeight: "780px",
    files: [{
      path: 'src/components/shadcn-space/blocks/login-01/page.tsx',
      type: "registry:page",
      target: 'app/login-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/login-01/login.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/login-01/login.tsx',
    },

    ],
    component: React.lazy(() => import('@/components/shadcn-space/blocks/login-01/page')),
    created_at: '2026-01-13T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.login],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'logo-cloud-01',
    title: 'Logo Cloud 01',
    description: 'A simple logo cloud built with Shadcn styling, using a subtle background, underlined heading, and a flexible grid of brand images that adapts smoothly across screen sizes.',
    type: "registry:block",
    dependencies: [""],
    registryDependencies: [],
    iframeHeight: "500px",
    files: [{
      path: 'src/components/shadcn-space/blocks/logo-cloud-01/page.tsx',
      type: "registry:page",
      target: 'app/logo-cloud-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/logo-cloud-01/logo-cloud.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/logo-cloud-01/logo-cloud.tsx',
    },
    {
      path: 'src/components/shadcn-space/animations/marquee.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/animations/marquee.tsx',
    }
    ],
    component: React.lazy(() => import('@/components/shadcn-space/blocks/logo-cloud-01/page')),
    created_at: '2026-01-20T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.logoCloud],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'register-01',
    title: 'Register 01 - Simple & Secure Signup Page',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=3678-6008&t=s6w7yYhqg5U0ajyZ-1",
    description: 'A streamlined signup page with Google and GitHub authentication, clean form fields, and conversion-focused layout, perfect for SaaS onboarding built with shadcn UI.',
    type: "registry:block",
    dependencies: [""],
    registryDependencies: [
      "card",
      "button",
      "input",
      "field"
    ],
    iframeHeight: "810px",
    files: [{
      path: 'src/components/shadcn-space/blocks/register-01/page.tsx',
      type: "registry:page",
      target: 'app/register-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/register-01/register.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/register-01/register.tsx',
    },

    ],
    component: React.lazy(() => import('@/components/shadcn-space/blocks/register-01/page')),
    created_at: '2026-01-15T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.register],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'table-01',
    title: 'Table 01 - Project Management Table',
    description: 'A sortable projects table with manager, team avatars, progress indicators, search, and pagination, ideal for admin dashboards to track project status and streamline team workflows efficiently.',
    type: "registry:block",
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=3678-5025&t=s6w7yYhqg5U0ajyZ-1",
    dependencies: ["lucide-react", "simplebar-react"],
    registryDependencies: ["card", "progress", "checkbox", "table", "dropdown-menu"],
    files: [{
      path: 'src/components/shadcn-space/blocks/table-01/page.tsx',
      type: "registry:page",
      target: 'app/table-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/table-01/table.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/table-01/table.tsx',
    }],
    component: React.lazy(() => import('@/components/shadcn-space/blocks/table-01/table')),
    created_at: '2025-12-10T18:53:10+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.tables],
    masterCategory: MasterCatAdmin,
  },
  {
    name: 'topbar-01',
    title: 'Topbar 01',
    description: 'A simple topbar block',
    type: "registry:block",
    dependencies: ["@iconify/react"],
    registryDependencies: ["sidebar", "button", "separator", "avatar", "dropdown-menu", "navigation-menu"],
    files: [{
      path: 'src/components/shadcn-space/blocks/topbar-01/page.tsx',
      type: "registry:page",
      target: 'app/topbar-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/topbar-01/dropdown-language.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/topbar-01/dropdown-language.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/topbar-01/dropdown-profile.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/topbar-01/dropdown-profile.tsx',
    }],
    component: React.lazy(() => import('@/components/shadcn-space/blocks/topbar-01/page')),
    created_at: '2025-12-17T18:53:10+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.topbars],
    masterCategory: MasterCatAdmin,
  },
  {
    name: 'two-factor-authentication-01',
    title: 'Two Factor Authentication 01 - Two-Factor Authentication Page',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=3678-6022&t=s6w7yYhqg5U0ajyZ-1",
    description: 'A secure two-factor authentication screen with one-time code inputs and resend option, adding an extra protection layer to your SaaS login and user accounts.',
    type: "registry:block",
    dependencies: [""],
    registryDependencies: [
      "card",
      "button",
      "field",
      "inputotp"
    ],
    iframeHeight: "555px",
    files: [{
      path: 'src/components/shadcn-space/blocks/two-factor-authentication-01/page.tsx',
      type: "registry:page",
      target: 'app/two-factor-authentication-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/two-factor-authentication-01/two-factor-auth.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/two-factor-authentication-01/two-factor-auth.tsx',
    },

    ],
    component: React.lazy(() => import('@/components/shadcn-space/blocks/two-factor-authentication-01/page')),
    created_at: '2026-01-15T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.twoFactorAuth],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'verify-email-01',
    title: 'Verify Email 01 - Email Verification Page',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=3678-6018&t=s6w7yYhqg5U0ajyZ-1",
    description: 'A clean email verification screen that confirms account activation, guides users to check their inbox, and offers resend functionality for a smooth onboarding experience.',
    type: "registry:block",
    dependencies: [""],
    registryDependencies: [
      "button",
      "card",
      "field",
    ],
    files: [{
      path: 'src/components/shadcn-space/blocks/verify-email-01/page.tsx',
      type: "registry:page",
      target: 'app/verify-email-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/verify-email-01/verify-email.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/verify-email-01/verify-email.tsx',
    },
    ],
    component: React.lazy(() => import('@/components/shadcn-space/blocks/verify-email-01/page')),
    created_at: '2026-01-15T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.verifyEmail],
    masterCategory: MasterCatWebsite,
  },
  {
    name: 'widget-01',
    title: 'Widget 01 - Analytics Overview Widget',
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=3678-4924&t=1YcME6jZvCdiVSmg-1",
    description: 'A compact analytics widget displaying earnings and expenses with growth indicators, perfect for admin dashboards to provide quick financial insights without overwhelming the interface.',
    type: "registry:block",
    dependencies: ["@iconify/react"],
    registryDependencies: ["card", "separator", "badge"],
    files: [{
      path: 'src/components/shadcn-space/blocks/widget-01/page.tsx',
      type: "registry:page",
      target: 'app/widget-01/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/widget-01/widget.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/widget-01/widget.tsx',
    }],
    component: React.lazy(
      () =>
        import('@/components/shadcn-space/blocks/widget-01/page')
    ),
    created_at: '2026-01-13T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.widgets],
    masterCategory: MasterCatAdmin,
  },
  {
    name: 'widget-02',
    title: 'Widget 02 - Sales by Country Widget',
    description: 'A ranked country wise sales widget with flags, revenue values, and growth indicators, ideal for dashboards to monitor geographic performance and spot emerging market trends quickly.',
    type: "registry:block",
    figmaLink: "https://www.figma.com/design/xN0ICHXEd4moz5sfE5no4r/shadcnspace-figma-uikit-free?node-id=3678-4925&t=s6w7yYhqg5U0ajyZ-1",
    dependencies: ["@iconify/react", "motion"],
    registryDependencies: ["card", "badge", "dropdown-menu", "separator"],
    files: [{
      path: 'src/components/shadcn-space/blocks/widget-02/page.tsx',
      type: "registry:page",
      target: 'app/widget-02/page.tsx',
    },
    {
      path: 'src/components/shadcn-space/blocks/widget-02/widget.tsx',
      type: "registry:component",
      target: 'components/shadcn-space/blocks/widget-02/widget.tsx',
    }],
    component: React.lazy(
      () =>
        import('@/components/shadcn-space/blocks/widget-02/page')
    ),
    created_at: '2026-01-13T17:42:25+05:30',
    isPro: false,
    isDraft: false,
    categories: [categories.widgets],
    masterCategory: MasterCatAdmin,
  },
];
