import { categories } from "./categories";

export const components = [
  {
    name: "apple-dock",
    title: "Default",
    description: "Apple Dock component",
    type: "registry:component",
    dependencies: ["motion", "lucide-react", "class-variance-authority"],
    files: [
      {
        path: "src/components/shadcn-space/apple-dock/apple-dock.tsx",
        type: "registry:component",
        target: "components/shadcn-space/apple-dock/apple-dock.tsx",
      },
    ],
    category: categories["apple-dock"],
  },
  {
    name: "orbiting-circles",
    title: "Default",
    description: "Orbiting Circles component",
    type: "registry:component",
    dependencies: ["lucide-react"],
    files: [
      {
        path: "src/components/shadcn-space/orbiting-circles/orbiting-circles.tsx",
        type: "registry:component",
        target: "components/shadcn-space/orbiting-circles/orbiting-circles.tsx",
      },
      {
        path: "src/components/shadcn-space/orbiting-circles/orbiting-circles.css",
        type: "registry:style",
        target: "components/shadcn-space/orbiting-circles/orbiting-circles.css",
      },
    ],
    category: categories["orbiting-circles"],
  },
  {
    name: "animated-list",
    title: "Default",
    description: "Animated List component",
    type: "registry:component",
    dependencies: ["motion"],
    files: [
      {
        path: "src/components/shadcn-space/animated-list/animated-list.tsx",
        type: "registry:component",
        target: "components/shadcn-space/animated-list/animated-list.tsx",
      },
    ],
    category: categories["animated-list"],
  },
  {
    name: "marquee-02",
    title: "Marquee-02 - Brands",
    description: "Brands marquee component",
    type: "registry:component",
    dependencies: [""],
    registryDependencies: [""],
    files: [
      {
        path: "src/components/shadcn-space/marquee/marquee-02.tsx",
        type: "registry:component",
        target: "components/shadcn-space/marquee/marquee-02.tsx",
      },
      {
        path: "src/components/shadcn-space/animations/marquee.tsx",
        type: "registry:component",
        target: "components/shadcn-space/animations/marquee.tsx",
      },
    ],
    category: categories["marquee"],
  },
  {
    name: "accordion-01",
    title: "Accordion-01 - Default",
    description: "Default accordion component",
    type: "registry:component",
    dependencies: ["lucide-react"],
    registryDependencies: ["accordion"],
    files: [
      {
        path: "src/components/shadcn-space/accordion/accordion-01.tsx",
        type: "registry:component",
        target: "components/shadcn-space/accordion/accordion-01.tsx",
      },
    ],
    category: categories["accordion"],
  },
  {
    name: "accordion-02",
    title: "Accordion-02 - Multi-level",
    description: "Multi-level accordion component",
    type: "registry:component",
    dependencies: ["lucide-react"],
    registryDependencies: ["accordion", "collapsible"],
    files: [
      {
        path: "src/components/shadcn-space/accordion/accordion-02.tsx",
        type: "registry:component",
        target: "components/shadcn-space/accordion/accordion-02.tsx",
      },
    ],
    category: categories["accordion"],
  },

  {
    name: "avatar-01",
    title: "Avatar-01 - Default",
    description: "Default avatar component",
    type: "registry:component",
    dependencies: [],
    registryDependencies: ["avatar"],
    files: [
      {
        path: "src/components/shadcn-space/avatar/avatar-01.tsx",
        type: "registry:component",
        target: "components/shadcn-space/avatar/avatar-01.tsx",
      },
    ],
    category: categories["avatar"],
  },

  {
    name: "avatar-02",
    title: "Avatar-02 - Group",
    description: "Group avatar component",
    type: "registry:component",
    dependencies: [],
    registryDependencies: ["avatar"],
    files: [
      {
        path: "src/components/shadcn-space/avatar/avatar-02.tsx",
        type: "registry:component",
        target: "components/shadcn-space/avatar/avatar-02.tsx",
      },
    ],
    category: categories["avatar"],
  },

  {
    name: "avatar-03",
    title: "Avatar-03 - Badge",
    description: "Badge avatar component",
    type: "registry:component",
    dependencies: ["lucide-react"],
    registryDependencies: ["avatar"],
    files: [
      {
        path: "src/components/shadcn-space/avatar/avatar-03.tsx",
        type: "registry:component",
        target: "components/shadcn-space/avatar/avatar-03.tsx",
      },
    ],
    category: categories["avatar"],
  },

  {
    name: "avatar-04",
    title: "Avatar-04 - Border",
    description: "Border avatar component",
    type: "registry:component",
    dependencies: ["lucide-react"],
    registryDependencies: ["avatar"],
    files: [
      {
        path: "src/components/shadcn-space/avatar/avatar-04.tsx",
        type: "registry:component",
        target: "components/shadcn-space/avatar/avatar-04.tsx",
      },
    ],
    category: categories["avatar"],
  },

  {
    name: "avatar-05",
    title: "Avatar-05 - Counter",
    description: "Counter avatar component",
    type: "registry:component",
    dependencies: [],
    registryDependencies: ["avatar"],
    files: [
      {
        path: "src/components/shadcn-space/avatar/avatar-05.tsx",
        type: "registry:component",
        target: "components/shadcn-space/avatar/avatar-05.tsx",
      },
    ],
    category: categories["avatar"],
  },
  {
    name: "avatar-06",
    title: "Avatar-06 - Fallback",
    description: "Fallback avatar component",
    type: "registry:component",
    dependencies: ["lucide-react"],
    registryDependencies: ["avatar"],
    files: [
      {
        path: "src/components/shadcn-space/avatar/avatar-06.tsx",
        type: "registry:component",
        target: "components/shadcn-space/avatar/avatar-06.tsx",
      },
    ],
    category: categories["avatar"],
  },
  {
    name: "button-01",
    title: "Button-01 - With Icon",
    description: "With Icon button component",
    type: "registry:component",
    dependencies: ["lucide-react"],
    registryDependencies: ["button"],
    files: [
      {
        path: "src/components/shadcn-space/button/button-01.tsx",
        type: "registry:component",
        target: "components/shadcn-space/button/button-01.tsx",
      },
    ],
    category: categories["button"],
  },
  {
    name: "button-02",
    title: "Button-02 - Shiny Text",
    description: "Shiny Text button component",
    type: "registry:component",
    dependencies: [],
    registryDependencies: ["button"],
    files: [
      {
        path: "src/components/shadcn-space/button/button-02.tsx",
        type: "registry:component",
        target: "components/shadcn-space/button/button-02.tsx",
      },
      {
        path: "src/components/shadcn-space/button/button-02.css",
        type: "registry:style",
        target: "components/shadcn-space/button/button-02.css",
      },
    ],
    category: categories["button"],
  },
  {
    name: "button-03",
    title: "Button-03 - Shine Hover",
    description: "Shine Hover button component",
    type: "registry:component",
    dependencies: [],
    registryDependencies: ["button"],
    files: [
      {
        path: "src/components/shadcn-space/button/button-03.tsx",
        type: "registry:component",
        target: "components/shadcn-space/button/button-03.tsx",
      },
    ],
    category: categories["button"],
  },
  {
    name: "button-04",
    title: "Button-04 - Heartbeat Effect",
    description: "Heartbeat Effect button component",
    type: "registry:component",
    dependencies: [],
    registryDependencies: ["button"],
    files: [
      {
        path: "src/components/shadcn-space/button/button-04.tsx",
        type: "registry:component",
        target: "components/shadcn-space/button/button-04.tsx",
      },
      {
        path: "src/components/shadcn-space/button/button-04.css",
        type: "registry:style",
        target: "components/shadcn-space/button/button-04.css",
      },
    ],
    category: categories["button"],
  },
  {
    name: "button-05",
    title: "Button-05 - Get Figma File",
    description: "Get Figma File button component",
    type: "registry:component",
    dependencies: [],
    registryDependencies: ["button"],
    files: [
      {
        path: "src/components/shadcn-space/button/button-05.tsx",
        type: "registry:component",
        target: "components/shadcn-space/button/button-05.tsx",
      },
    ],
    category: categories["button"],
  },
  {
    name: "button-06",
    title: "Button-06 - Animated Border",
    description: "Animated Border button component",
    type: "registry:component",
    dependencies: ["lucide-react"],
    registryDependencies: ["button"],
    files: [
      {
        path: "src/components/shadcn-space/button/button-06.tsx",
        type: "registry:component",
        target: "components/shadcn-space/button/button-06.tsx",
      },
    ],
    category: categories["button"],
  },
  {
    name: "button-07",
    title: "Button-07 - Social",
    description: "Social button component",
    type: "registry:component",
    dependencies: [],
    registryDependencies: ["button"],
    files: [
      {
        path: "src/components/shadcn-space/button/button-07.tsx",
        type: "registry:component",
        target: "components/shadcn-space/button/button-07.tsx",
      },
    ],
    category: categories["button"],
  },
  {
    name: "button-08",
    title: "Button-08 - Social Icon",
    description: "Social Icon button component",
    type: "registry:component",
    dependencies: [],
    registryDependencies: ["button"],
    files: [
      {
        path: "src/components/shadcn-space/button/button-08.tsx",
        type: "registry:component",
        target: "components/shadcn-space/button/button-08.tsx",
      },
    ],
    category: categories["button"],
  },
  {
    name: "button-09",
    title: "Button-09 - Outline With Icon",
    description: "Outline With Icon button component",
    type: "registry:component",
    dependencies: ["lucide-react"],
    registryDependencies: ["button"],
    files: [
      {
        path: "src/components/shadcn-space/button/button-09.tsx",
        type: "registry:component",
        target: "components/shadcn-space/button/button-09.tsx",
      },
    ],
    category: categories["button"],
  },
  {
    name: "button-10",
    title: "Button-10 - Save",
    description: "Save button component",
    type: "registry:component",
    dependencies: ["lucide-react"],
    registryDependencies: ["button"],
    files: [
      {
        path: "src/components/shadcn-space/button/button-10.tsx",
        type: "registry:component",
        target: "components/shadcn-space/button/button-10.tsx",
      },
    ],
    category: categories["button"],
  },
  {
    name: "button-11",
    title: "Button-11 - Cancel",
    description: "Cancel button component",
    type: "registry:component",
    dependencies: ["lucide-react"],
    registryDependencies: ["button"],
    files: [
      {
        path: "src/components/shadcn-space/button/button-11.tsx",
        type: "registry:component",
        target: "components/shadcn-space/button/button-11.tsx",
      },
    ],
    category: categories["button"],
  },
  {
    name: "button-12",
    title: "Button-12 - Default",
    description: "Default button component",
    type: "registry:component",
    dependencies: [],
    registryDependencies: ["button"],
    files: [
      {
        path: "src/components/shadcn-space/button/button-12.tsx",
        type: "registry:component",
        target: "components/shadcn-space/button/button-12.tsx",
      },
    ],
    category: categories["button"],
  },
  {
    name: "button-13",
    title: "Button-13 - Size xs",
    description: "Size xs button component",
    type: "registry:component",
    dependencies: [],
    registryDependencies: ["button"],
    files: [
      {
        path: "src/components/shadcn-space/button/button-13.tsx",
        type: "registry:component",
        target: "components/shadcn-space/button/button-13.tsx",
      },
    ],
    category: categories["button"],
  },
  {
    name: "button-14",
    title: "Button-14 - Size sm",
    description: "Size sm button component",
    type: "registry:component",
    dependencies: [],
    registryDependencies: ["button"],
    files: [
      {
        path: "src/components/shadcn-space/button/button-14.tsx",
        type: "registry:component",
        target: "components/shadcn-space/button/button-14.tsx",
      },
    ],
    category: categories["button"],
  },
  {
    name: "button-15",
    title: "Button-15 - Size lg",
    description: "Size lg button component",
    type: "registry:component",
    dependencies: [],
    registryDependencies: ["button"],
    files: [
      {
        path: "src/components/shadcn-space/button/button-15.tsx",
        type: "registry:component",
        target: "components/shadcn-space/button/button-15.tsx",
      },
    ],
    category: categories["button"],
  },
  {
    name: "badge-01",
    title: "Badge-01 - Default",
    description: "Badge component",
    type: "registry:component",
    dependencies: [],
    registryDependencies: ["badge"],
    files: [
      {
        path: "src/components/shadcn-space/badge/badge-01.tsx",
        type: "registry:component",
        target: "components/shadcn-space/badge/badge-01.tsx",
      },
    ],
    category: categories["badge"],
  },

  {
    name: "badge-02",
    title: "Badge-02 - Count",
    description: "Badge component",
    type: "registry:component",
    dependencies: [],
    registryDependencies: ["badge"],
    files: [
      {
        path: "src/components/shadcn-space/badge/badge-02.tsx",
        type: "registry:component",
        target: "components/shadcn-space/badge/badge-02.tsx",
      },
    ],
    category: categories["badge"],
  },
  {
    name: "badge-03",
    title: "Badge-03 - Outline",
    description: "Badge component",
    type: "registry:component",
    dependencies: [],
    registryDependencies: ["badge"],
    files: [
      {
        path: "src/components/shadcn-space/badge/badge-03.tsx",
        type: "registry:component",
        target: "components/shadcn-space/badge/badge-03.tsx",
      },
    ],
    category: categories["badge"],
  },
  {
    name: "badge-04",
    title: "Badge-04 - With Icon",
    description: "Badge component",
    type: "registry:component",
    dependencies: ["lucide-react"],
    registryDependencies: ["badge"],
    files: [
      {
        path: "src/components/shadcn-space/badge/badge-04.tsx",
        type: "registry:component",
        target: "components/shadcn-space/badge/badge-04.tsx",
      },
    ],
    category: categories["badge"],
  },
  {
    name: "badge-05",
    title: "Badge-05 - Link",
    description: "Badge component",
    type: "registry:component",
    dependencies: ["lucide-react"],
    registryDependencies: ["badge"],
    files: [
      {
        path: "src/components/shadcn-space/badge/badge-05.tsx",
        type: "registry:component",
        target: "components/shadcn-space/badge/badge-05.tsx",
      },
    ],
    category: categories["badge"],
  },
  {
    name: "badge-06",
    title: "Badge-06 - Error",
    description: "Badge component",
    type: "registry:component",
    dependencies: [],
    registryDependencies: ["badge"],
    files: [
      {
        path: "src/components/shadcn-space/badge/badge-06.tsx",
        type: "registry:component",
        target: "components/shadcn-space/badge/badge-06.tsx",
      },
    ],
    category: categories["badge"],
  },

  {
    name: "calendar-01",
    title: "Calendar 01 - Standard calendar",
    description: "Calendar component",
    type: "registry:component",
    registryDependencies: ["calendar"],
    dependencies: ["faker"],
    files: [
      {
        path: "src/components/shadcn-space/calendar/calendar-01.tsx",
        type: "registry:component",
        target: "components/shadcn-space/calendar/calendar-01.tsx",
      },
    ],
    category: categories["calendar"],
  },

  {
    name: "calendar-02",
    title: "Calendar 02 - Style calendar",
    description: "Calendar component",
    type: "registry:component",
    registryDependencies: ["calendar"],
    dependencies: ["faker"],
    files: [
      {
        path: "src/components/shadcn-space/calendar/calendar-02.tsx",
        type: "registry:component",
        target: "components/shadcn-space/calendar/calendar-02.tsx",
      },
    ],
    category: categories["calendar"],
  },

  {
    name: "calendar-03",
    title: "Calendar 03 - Time calendar",
    description: "Calendar component",
    type: "registry:component",
    registryDependencies: ["calendar", "scrollarea", "button"],
    dependencies: [""],
    files: [
      {
        path: "src/components/shadcn-space/calendar/calendar-03.tsx",
        type: "registry:component",
        target: "components/shadcn-space/calendar/calendar-03.tsx",
      },
    ],
    category: categories["calendar"],
  },

  {
    name: "calendar-04",
    title: "Calendar 04 - Dialog calendar",
    description: "Calendar component",
    type: "registry:component",
    registryDependencies: ["calendar", "dialog", "button"],
    dependencies: ["faker", "daterange"],
    files: [
      {
        path: "src/components/shadcn-space/calendar/calendar-04.tsx",
        type: "registry:component",
        target: "components/shadcn-space/calendar/calendar-04.tsx",
      },
    ],
    category: categories["calendar"],
  },

  {
    name: "tooltip-01",
    title: "Tooltip-01 - Hover Blog Card",
    description: "Tooltip component",
    type: "registry:component",
    registryDependencies: ["tooltip", "hover-card", "button"],
    dependencies: ["lucid"],
    files: [
      {
        path: "src/components/shadcn-space/tooltip/tooltip-01.tsx",
        type: "registry:component",
        target: "components/shadcn-space/tooltip/tooltip-01.tsx",
      },
    ],
    category: categories["tooltip"],
  },

  {
    name: "tooltip-02",
    title: "Tooltip-02 - Content Tooltip",
    description: "Tooltip component",
    type: "registry:component",
    registryDependencies: ["tooltip", "button"],
    dependencies: ["lucid"],
    files: [
      {
        path: "src/components/shadcn-space/tooltip/tooltip-02.tsx",
        type: "registry:component",
        target: "components/shadcn-space/tooltip/tooltip-02.tsx",
      },
    ],
    category: categories["tooltip"],
  },
  {
    name: "tooltip-03",
    title: "Tooltip-03 - Animated Tooltip",
    description: "Animated Tooltip component",
    type: "registry:component",
    registryDependencies: [],
    dependencies: ["motion"],
    files: [
      {
        path: "src/components/shadcn-space/tooltip/tooltip-03.tsx",
        type: "registry:component",
        target: "components/shadcn-space/tooltip/tooltip-03.tsx",
      },
    ],
    category: categories["tooltip"],
  },
  {
    name: "tooltip-04",
    title: "Tooltip-04 - Rounded Tooltip",
    description: "Tooltip component",
    type: "registry:component",
    registryDependencies: ["tooltip", "button"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/tooltip/tooltip-04.tsx",
        type: "registry:component",
        target: "components/shadcn-space/tooltip/tooltip-04.tsx",
      },
    ],
    category: categories["tooltip"],
  },
  {
    name: "tooltip-05",
    title: "Tooltip-05 - Tooltip Position",
    description: "Tooltip component",
    type: "registry:component",
    registryDependencies: ["tooltip", "button"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/tooltip/tooltip-05.tsx",
        type: "registry:component",
        target: "components/shadcn-space/tooltip/tooltip-05.tsx",
      },
    ],
    category: categories["tooltip"],
  },
  {
    name: "tooltip-06",
    title: "Tooltip-06 - Avatar Tooltip",
    description: "Tooltip component",
    type: "registry:component",
    registryDependencies: ["tooltip", "button", "avatar"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/tooltip/tooltip-06.tsx",
        type: "registry:component",
        target: "components/shadcn-space/tooltip/tooltip-06.tsx",
      },
    ],
    category: categories["tooltip"],
  },
  {
    name: "tooltip-07",
    title: "Tooltip-07 - Error Tooltip",
    description: "Tooltip component",
    type: "registry:component",
    registryDependencies: ["tooltip", "button"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/tooltip/tooltip-07.tsx",
        type: "registry:component",
        target: "components/shadcn-space/tooltip/tooltip-07.tsx",
      },
    ],
    category: categories["tooltip"],
  },
  {
    name: "animated-text-01",
    title: "Animated Text-01 - Shiny Text",
    description: "Animated Text component",
    type: "registry:component",
    registryDependencies: [],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/animated-text/animated-text-01.tsx",
        type: "registry:component",
        target: "components/shadcn-space/animated-text/animated-text-01.tsx",
      },
      {
        path: "src/components/shadcn-space/animated-text/animated-text-01.css",
        type: "registry:component",
        target: "components/shadcn-space/animated-text/animated-text-01.css",
      },
    ],
    category: categories["animated-text"],
  },
  {
    name: "animated-text-02",
    title: "Animated Text-02 - Gradient Text",
    description: "Animated Gradient Text component",
    type: "registry:component",
    registryDependencies: [],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/animated-text/animated-text-02.tsx",
        type: "registry:component",
        target: "components/shadcn-space/animated-text/animated-text-02.tsx",
      },
    ],
    category: categories["animated-text"],
  },
  {
    name: "animated-text-03",
    title: "Animated Text-03 - Typing",
    description: "Animated Typing component",
    type: "registry:component",
    registryDependencies: [],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/animated-text/animated-text-03.tsx",
        type: "registry:component",
        target: "components/shadcn-space/animated-text/animated-text-03.tsx",
      },
    ],
    category: categories["animated-text"],
  },
  {
    name: "animated-text-04",
    title: "Animated Text-04 - Rolling Text",
    description: "Animated Rolling Text component",
    type: "registry:component",
    registryDependencies: [],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/animated-text/animated-text-04.tsx",
        type: "registry:component",
        target: "components/shadcn-space/animated-text/animated-text-04.tsx",
      },
    ],
    category: categories["animated-text"],
  },
  {
    name: "animated-text-05",
    title: "Animated Text-05 - Shimmer Text",
    description: "Animated Shimmer Text component",
    type: "registry:component",
    registryDependencies: [],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/animated-text/animated-text-05.tsx",
        type: "registry:component",
        target: "components/shadcn-space/animated-text/animated-text-05.tsx",
      },
    ],
    category: categories["animated-text"],
  },

  {
    name: "input-01",
    title: "Input-01 - Input with date",
    description: "Input component",
    type: "registry:component",
    registryDependencies: ["input", "label"],
    dependencies: ["lucide-react"],
    files: [
      {
        path: "src/components/shadcn-space/input/input-01.tsx",
        type: "registry:component",
        target: "components/shadcn-space/input/input-01.tsx",
      },
    ],
    category: categories["input"],
  },
  {
    name: "input-02",
    title: "Input-02 - Input with time",
    description: "Input component",
    type: "registry:component",
    registryDependencies: ["input", "label"],
    dependencies: ["lucide-react"],
    files: [
      {
        path: "src/components/shadcn-space/input/input-02.tsx",
        type: "registry:component",
        target: "components/shadcn-space/input/input-02.tsx",
      },
    ],
    category: categories["input"],
  },
  {
    name: "input-03",
    title: "Input-03 - Input with currency",
    description: "Input component",
    type: "registry:component",
    registryDependencies: ["input", "label"],
    dependencies: ["lucide-react"],
    files: [
      {
        path: "src/components/shadcn-space/input/input-03.tsx",
        type: "registry:component",
        target: "components/shadcn-space/input/input-03.tsx",
      },
    ],
    category: categories["input"],
  },
  {
    name: "input-04",
    title: "Input-04 - Real Time Validation",
    description: "Input component",
    type: "registry:component",
    registryDependencies: ["input"],
    dependencies: ["lucide-react"],
    files: [
      {
        path: "src/components/shadcn-space/input/input-04.tsx",
        type: "registry:component",
        target: "components/shadcn-space/input/input-04.tsx",
      },
    ],
    category: categories["input"],
  },
  {
    name: "input-05",
    title: "Input-05 - Input with start select",
    description: "Input component",
    type: "registry:component",
    registryDependencies: ["input", "select", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/input/input-05.tsx",
        type: "registry:component",
        target: "components/shadcn-space/input/input-05.tsx",
      },
    ],
    category: categories["input"],
  },
  {
    name: "input-06",
    title: "Input-06 - Input with character counter",
    description: "Input component",
    type: "registry:component",
    registryDependencies: ["input", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/input/input-06.tsx",
        type: "registry:component",
        target: "components/shadcn-space/input/input-06.tsx",
      },
    ],
    category: categories["input"],
  },
  {
    name: "input-07",
    title: "Input-07 - Input with controls",
    description: "Input component",
    type: "registry:component",
    registryDependencies: ["button", "input", "label"],
    dependencies: ["lucide-react"],
    files: [
      {
        path: "src/components/shadcn-space/input/input-07.tsx",
        type: "registry:component",
        target: "components/shadcn-space/input/input-07.tsx",
      },
    ],
    category: categories["input"],
  },
  {
    name: "input-08",
    title: "Input-08 - Input with add-ons",
    description: "Input component",
    type: "registry:component",
    registryDependencies: ["input", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/input/input-08.tsx",
        type: "registry:component",
        target: "components/shadcn-space/input/input-08.tsx",
      },
    ],
    category: categories["input"],
  },
  {
    name: "input-09",
    title: "Input-09 - Input with floating label",
    description: "Input component",
    type: "registry:component",
    registryDependencies: ["input", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/input/input-09.tsx",
        type: "registry:component",
        target: "components/shadcn-space/input/input-09.tsx",
      },
    ],
    category: categories["input"],
  },
  {
    name: "input-10",
    title: "Input-10 - Input with clear button",
    description: "Input component",
    type: "registry:component",
    registryDependencies: ["button", "input", "label"],
    dependencies: ["lucide-react"],
    files: [
      {
        path: "src/components/shadcn-space/input/input-10.tsx",
        type: "registry:component",
        target: "components/shadcn-space/input/input-10.tsx",
      },
    ],
    category: categories["input"],
  },
  {
    name: "input-11",
    title: "Input-11 - Input with end inline button",
    description: "Input component",
    type: "registry:component",
    registryDependencies: ["button", "input", "label"],
    dependencies: ["lucide-react"],
    files: [
      {
        path: "src/components/shadcn-space/input/input-11.tsx",
        type: "registry:component",
        target: "components/shadcn-space/input/input-11.tsx",
      },
    ],
    category: categories["input"],
  },
  {
    name: "input-12",
    title: "Input-12 - Input with end button",
    description: "Input component",
    type: "registry:component",
    registryDependencies: ["button", "input", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/input/input-12.tsx",
        type: "registry:component",
        target: "components/shadcn-space/input/input-12.tsx",
      },
    ],
    category: categories["input"],
  },
  {
    name: "input-13",
    title: "Input-13 - Input with file",
    description: "Input component",
    type: "registry:component",
    registryDependencies: ["input", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/input/input-13.tsx",
        type: "registry:component",
        target: "components/shadcn-space/input/input-13.tsx",
      },
    ],
    category: categories["input"],
  },
  {
    name: "input-14",
    title: "Input-14 - Input with error",
    description: "Input component",
    type: "registry:component",
    registryDependencies: ["input", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/input/input-14.tsx",
        type: "registry:component",
        target: "components/shadcn-space/input/input-14.tsx",
      },
    ],
    category: categories["input"],
  },
  {
    name: "input-15",
    title: "Input-15 - Required Input",
    description: "Input component",
    type: "registry:component",
    registryDependencies: ["input", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/input/input-15.tsx",
        type: "registry:component",
        target: "components/shadcn-space/input/input-15.tsx",
      },
    ],
    category: categories["input"],
  },
  {
    name: "input-16",
    title: "Input-16 - Standard Input",
    description: "Input component",
    type: "registry:component",
    registryDependencies: ["input"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/input/input-16.tsx",
        type: "registry:component",
        target: "components/shadcn-space/input/input-16.tsx",
      },
    ],
    category: categories["input"],
  },
  {
    name: "input-17",
    title: "Input-17 - Input with label",
    description: "Input component",
    type: "registry:component",
    registryDependencies: ["input", "label"],
    dependencies: ["lucide-react"],
    files: [
      {
        path: "src/components/shadcn-space/input/input-17.tsx",
        type: "registry:component",
        target: "components/shadcn-space/input/input-17.tsx",
      },
    ],
    category: categories["input"],
  },
  {
    name: "input-18",
    title: "Input-18 - Disabled",
    description: "Input component",
    type: "registry:component",
    registryDependencies: ["input"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/input/input-18.tsx",
        type: "registry:component",
        target: "components/shadcn-space/input/input-18.tsx",
      },
    ],
    category: categories["input"],
  },
  {
    name: "textarea-01",
    title: "Textarea-01 - Feedback Textarea",
    description: "Textarea component",
    type: "registry:component",
    registryDependencies: ["textarea"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/textarea/textarea-01.tsx",
        type: "registry:component",
        target: "components/shadcn-space/textarea/textarea-01.tsx",
      },
    ],
    category: categories["textarea"],
  },
  {
    name: "textarea-02",
    title: "Textarea-02 - Textarea with icon",
    description: "Textarea component",
    type: "registry:component",
    registryDependencies: ["textarea", "label"],
    dependencies: ["lucide-react"],
    files: [
      {
        path: "src/components/shadcn-space/textarea/textarea-02.tsx",
        type: "registry:component",
        target: "components/shadcn-space/textarea/textarea-02.tsx",
      },
    ],
    category: categories["textarea"],
  },
  {
    name: "textarea-03",
    title: "Textarea-03 - Required Textarea",
    description: "Textarea component",
    type: "registry:component",
    registryDependencies: ["textarea", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/textarea/textarea-03.tsx",
        type: "registry:component",
        target: "components/shadcn-space/textarea/textarea-03.tsx",
      },
    ],
    category: categories["textarea"],
  },
  {
    name: "textarea-04",
    title: "Textarea-04 - Textarea with button",
    description: "Textarea component",
    type: "registry:component",
    registryDependencies: ["textarea", "label", "button"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/textarea/textarea-04.tsx",
        type: "registry:component",
        target: "components/shadcn-space/textarea/textarea-04.tsx",
      },
    ],
    category: categories["textarea"],
  },
  {
    name: "textarea-05",
    title: "Textarea-05 - Auto growing textarea",
    description: "Textarea component",
    type: "registry:component",
    registryDependencies: ["textarea", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/textarea/textarea-05.tsx",
        type: "registry:component",
        target: "components/shadcn-space/textarea/textarea-05.tsx",
      },
    ],
    category: categories["textarea"],
  },
  {
    name: "textarea-06",
    title: "Textarea-06 - Textarea with characters left",
    description: "Textarea component",
    type: "registry:component",
    registryDependencies: ["textarea", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/textarea/textarea-06.tsx",
        type: "registry:component",
        target: "components/shadcn-space/textarea/textarea-06.tsx",
      },
    ],
    category: categories["textarea"],
  },
  {
    name: "textarea-07",
    title: "Textarea-07 - Textarea with floating label",
    description: "Textarea component",
    type: "registry:component",
    registryDependencies: ["textarea", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/textarea/textarea-07.tsx",
        type: "registry:component",
        target: "components/shadcn-space/textarea/textarea-07.tsx",
      },
    ],
    category: categories["textarea"],
  },
  {
    name: "textarea-08",
    title: "Textarea-08 - Textarea with helper text",
    description: "Textarea component",
    type: "registry:component",
    registryDependencies: ["textarea", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/textarea/textarea-08.tsx",
        type: "registry:component",
        target: "components/shadcn-space/textarea/textarea-08.tsx",
      },
    ],
    category: categories["textarea"],
  },
  {
    name: "textarea-09",
    title: "Textarea-09 - Disabled Textarea",
    description: "Textarea component",
    type: "registry:component",
    registryDependencies: ["textarea", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/textarea/textarea-09.tsx",
        type: "registry:component",
        target: "components/shadcn-space/textarea/textarea-09.tsx",
      },
    ],
    category: categories["textarea"],
  },
  {
    name: "select-01",
    title: "Select-01 - Required select",
    description: "Select component",
    type: "registry:component",
    registryDependencies: ["select", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/select/select-01.tsx",
        type: "registry:component",
        target: "components/shadcn-space/select/select-01.tsx",
      },
    ],
    category: categories["select"],
  },
  {
    name: "select-02",
    title: "Select-02 - Select with icon",
    description: "Select component",
    type: "registry:component",
    registryDependencies: ["select", "label"],
    dependencies: ["lucide-react"],
    files: [
      {
        path: "src/components/shadcn-space/select/select-02.tsx",
        type: "registry:component",
        target: "components/shadcn-space/select/select-02.tsx",
      },
    ],
    category: categories["select"],
  },
  {
    name: "select-03",
    title: "Select-03 - Select with status",
    description: "Select component",
    type: "registry:component",
    registryDependencies: ["select", "label"],
    dependencies: ["lucide-react"],
    files: [
      {
        path: "src/components/shadcn-space/select/select-03.tsx",
        type: "registry:component",
        target: "components/shadcn-space/select/select-03.tsx",
      },
    ],
    category: categories["select"],
  },
  {
    name: "select-04",
    title: "Select-04 - Select with timezone",
    description: "Select component",
    type: "registry:component",
    registryDependencies: ["select", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/select/select-04.tsx",
        type: "registry:component",
        target: "components/shadcn-space/select/select-04.tsx",
      },
    ],
    category: categories["select"],
  },
  {
    name: "select-05",
    title: "Select-05 - Select with overlapping label",
    description: "Select component",
    type: "registry:component",
    registryDependencies: ["select"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/select/select-05.tsx",
        type: "registry:component",
        target: "components/shadcn-space/select/select-05.tsx",
      },
    ],
    category: categories["select"],
  },
  {
    name: "select-06",
    title: "Select-06 - Select with multiple options",
    description: "Select component",
    type: "registry:component",
    registryDependencies: ["label", "multi-select"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/select/select-06.tsx",
        type: "registry:component",
        target: "components/shadcn-space/select/select-06.tsx",
      },
      {
        path: "src/components/ui/multi-select.tsx",
        type: "registry:component",
        target: "components/ui/multi-select.tsx",
      },
    ],
    category: categories["select"],
  },
  {
    name: "select-07",
    title: "Select-07 - Select with avatars",
    description: "Select component",
    type: "registry:component",
    registryDependencies: ["select", "label", "avatar"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/select/select-07.tsx",
        type: "registry:component",
        target: "components/shadcn-space/select/select-07.tsx",
      },
    ],
    category: categories["select"],
  },
  {
    name: "select-08",
    title: "Select-08 - Select with leading text",
    description: "Select component",
    type: "registry:component",
    registryDependencies: ["select", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/select/select-08.tsx",
        type: "registry:component",
        target: "components/shadcn-space/select/select-08.tsx",
      },
    ],
    category: categories["select"],
  },
  {
    name: "select-09",
    title: "Select-09 - Select with separator",
    description: "Select component",
    type: "registry:component",
    registryDependencies: ["select", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/select/select-09.tsx",
        type: "registry:component",
        target: "components/shadcn-space/select/select-09.tsx",
      },
    ],
    category: categories["select"],
  },
  {
    name: "checkbox-01",
    title: "Checkbox-01 - Checkbox with sizes",
    description: "Checkbox component",
    type: "registry:component",
    registryDependencies: ["checkbox"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/checkbox/checkbox-01.tsx",
        type: "registry:component",
        target: "components/shadcn-space/checkbox/checkbox-01.tsx",
      },
    ],
    category: categories["checkbox"],
  },
  {
    name: "checkbox-02",
    title: "Checkbox-02 - Checkbox with vertical group",
    description: "Checkbox component",
    type: "registry:component",
    registryDependencies: ["checkbox"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/checkbox/checkbox-02.tsx",
        type: "registry:component",
        target: "components/shadcn-space/checkbox/checkbox-02.tsx",
      },
    ],
    category: categories["checkbox"],
  },
  {
    name: "checkbox-03",
    title: "Checkbox-03 - Checkbox with colors",
    description: "Checkbox component",
    type: "registry:component",
    registryDependencies: ["checkbox", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/checkbox/checkbox-03.tsx",
        type: "registry:component",
        target: "components/shadcn-space/checkbox/checkbox-03.tsx",
      },
    ],
    category: categories["checkbox"],
  },
  {
    name: "checkbox-04",
    title: "Checkbox-04 - Checkbox with todo list",
    description: "Checkbox component",
    type: "registry:component",
    registryDependencies: ["checkbox", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/checkbox/checkbox-04.tsx",
        type: "registry:component",
        target: "components/shadcn-space/checkbox/checkbox-04.tsx",
      },
    ],
    category: categories["checkbox"],
  },
  {
    name: "checkbox-05",
    title: "Checkbox-05 - Checkbox with list group",
    description: "Checkbox component",
    type: "registry:component",
    registryDependencies: ["checkbox", "label"],
    dependencies: ["lucide-react"],
    files: [
      {
        path: "src/components/shadcn-space/checkbox/checkbox-05.tsx",
        type: "registry:component",
        target: "components/shadcn-space/checkbox/checkbox-05.tsx",
      },
    ],
    category: categories["checkbox"],
  },
  {
    name: "checkbox-06",
    title: "Checkbox-06 - Checkbox with form",
    description: "Checkbox component",
    type: "registry:component",
    registryDependencies: ["checkbox", "label", "button"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/checkbox/checkbox-06.tsx",
        type: "registry:component",
        target: "components/shadcn-space/checkbox/checkbox-06.tsx",
      },
    ],
    category: categories["checkbox"],
  },
  {
    name: "checkbox-07",
    title: "Checkbox-07 - Checkbox with custom icons",
    description: "Checkbox component",
    type: "registry:component",
    registryDependencies: ["checkbox"],
    dependencies: ["lucide-react"],
    files: [
      {
        path: "src/components/shadcn-space/checkbox/checkbox-07.tsx",
        type: "registry:component",
        target: "components/shadcn-space/checkbox/checkbox-07.tsx",
      },
    ],
    category: categories["checkbox"],
  },
  {
    name: "checkbox-08",
    title: "Checkbox-08 - Checkbox with dashed border",
    description: "Checkbox component",
    type: "registry:component",
    registryDependencies: ["checkbox", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/checkbox/checkbox-08.tsx",
        type: "registry:component",
        target: "components/shadcn-space/checkbox/checkbox-08.tsx",
      },
    ],
    category: categories["checkbox"],
  },
  {
    name: "checkbox-09",
    title: "Checkbox-09 - Checkbox with tree",
    description: "Checkbox component",
    type: "registry:component",
    registryDependencies: ["checkbox", "label"],
    dependencies: ["lucide-react"],
    files: [
      {
        path: "src/components/shadcn-space/checkbox/checkbox-09.tsx",
        type: "registry:component",
        target: "components/shadcn-space/checkbox/checkbox-09.tsx",
      },
    ],
    category: categories["checkbox"],
  },
  {
    name: "radio-group-01",
    title: "Radio Group-01 - Radio Group with tree",
    description: "Radio Group component",
    type: "registry:component",
    registryDependencies: ["label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/radio-group/radio-group-01.tsx",
        type: "registry:component",
        target: "components/shadcn-space/radio-group/radio-group-01.tsx",
      },
      {
        path: "src/components/ui/motion-radio-group.tsx",
        type: "registry:component",
        target: "components/ui/motion-radio-group.tsx",
      },
    ],
    category: categories["radio-group"],
  },
  {
    name: "radio-group-02",
    title: "Radio Group-02 - Radio Group with tree",
    description: "Radio Group component",
    type: "registry:component",
    registryDependencies: ["label", "radio-group"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/radio-group/radio-group-02.tsx",
        type: "registry:component",
        target: "components/shadcn-space/radio-group/radio-group-02.tsx",
      },
    ],
    category: categories["radio-group"],
  },
  {
    name: "radio-group-03",
    title: "Radio Group-03 - Radio Group with tree",
    description: "Radio Group component",
    type: "registry:component",
    registryDependencies: ["label", "radio-group"],
    dependencies: ["lucide-react"],
    files: [
      {
        path: "src/components/shadcn-space/radio-group/radio-group-03.tsx",
        type: "registry:component",
        target: "components/shadcn-space/radio-group/radio-group-03.tsx",
      },
    ],
    category: categories["radio-group"],
  },
  {
    name: "radio-group-04",
    title: "Radio Group-04 - Radio Group with tree",
    description: "Radio Group component",
    type: "registry:component",
    registryDependencies: ["label", "radio-group"],
    dependencies: ["lucide-react"],
    files: [
      {
        path: "src/components/shadcn-space/radio-group/radio-group-04.tsx",
        type: "registry:component",
        target: "components/shadcn-space/radio-group/radio-group-04.tsx",
      },
    ],
    category: categories["radio-group"],
  },
  {
    name: "radio-group-05",
    title: "Radio Group-05 - Radio Group with tree",
    description: "Radio Group component",
    type: "registry:component",
    registryDependencies: ["label", "radio-group"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/radio-group/radio-group-05.tsx",
        type: "registry:component",
        target: "components/shadcn-space/radio-group/radio-group-05.tsx",
      },
    ],
    category: categories["radio-group"],
  },
  {
    name: "radio-group-06",
    title: "Radio Group-06 - Radio Group with tree",
    description: "Radio Group component",
    type: "registry:component",
    registryDependencies: ["badge", "label", "radio-group"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/radio-group/radio-group-06.tsx",
        type: "registry:component",
        target: "components/shadcn-space/radio-group/radio-group-06.tsx",
      },
    ],
    category: categories["radio-group"],
  },
  {
    name: "switch-01",
    title: "Switch-01 - Active effect",
    description: "Switch with active effect component",
    type: "registry:component",
    registryDependencies: ["switch", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/switch/switch-01.tsx",
        type: "registry:component",
        target: "components/shadcn-space/switch/switch-01.tsx",
      },
    ],
    category: categories["switch"],
  },
  {
    name: "switch-02",
    title: "Switch-02 - With Icon",
    description: "Switch component",
    type: "registry:component",
    registryDependencies: ["switch", "label"],
    dependencies: ["lucide-react"],
    files: [
      {
        path: "src/components/shadcn-space/switch/switch-02.tsx",
        type: "registry:component",
        target: "components/shadcn-space/switch/switch-02.tsx",
      },
    ],
    category: categories["switch"],
  },
  {
    name: "switch-03",
    title: "Switch-03 - Toggle theme",
    description: "Switch toggle theme component",
    type: "registry:component",
    registryDependencies: ["switch"],
    dependencies: ["lucide-react"],
    files: [
      {
        path: "src/components/shadcn-space/switch/switch-03.tsx",
        type: "registry:component",
        target: "components/shadcn-space/switch/switch-03.tsx",
      },
    ],
    category: categories["switch"],
  },
  {
    name: "switch-04",
    title: "Switch-04 - With Description",
    description: "Switch component",
    type: "registry:component",
    registryDependencies: ["switch", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/switch/switch-04.tsx",
        type: "registry:component",
        target: "components/shadcn-space/switch/switch-04.tsx",
      },
    ],
    category: categories["switch"],
  },
  {
    name: "switch-05",
    title: "Switch-05 - With label",
    description: "Switch component",
    type: "registry:component",
    registryDependencies: ["switch", "label"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/switch/switch-05.tsx",
        type: "registry:component",
        target: "components/shadcn-space/switch/switch-05.tsx",
      },
    ],
    category: categories["switch"],
  },
  {
    name: "switch-06",
    title: "Switch-06 - Custom Colors",
    description: "Switch component",
    type: "registry:component",
    registryDependencies: ["switch"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/switch/switch-06.tsx",
        type: "registry:component",
        target: "components/shadcn-space/switch/switch-06.tsx",
      },
    ],
    category: categories["switch"],
  },
  {
    name: "tabs-01",
    title: "Tabs-01 - Animated",
    description: "Tabs component",
    type: "registry:component",
    registryDependencies: [],
    dependencies: ["motion"],
    files: [
      {
        path: "src/components/shadcn-space/tabs/tabs-01.tsx",
        type: "registry:component",
        target: "components/shadcn-space/tabs/tabs-01.tsx",
      },
    ],
    category: categories["tabs"],
  },
  {
    name: "tabs-02",
    title: "Tabs-02 - Transition",
    description: "Tabs component",
    type: "registry:component",
    registryDependencies: [],
    dependencies: ["motion"],
    files: [
      {
        path: "src/components/shadcn-space/tabs/tabs-02.tsx",
        type: "registry:component",
        target: "components/shadcn-space/tabs/tabs-02.tsx",
      },
    ],
    category: categories["tabs"],
  },
  {
    name: "tabs-03",
    title: "Tabs-03 - With Icon",
    description: "Tabs component",
    type: "registry:component",
    registryDependencies: ["tabs"],
    dependencies: ["lucide-react"],
    files: [
      {
        path: "src/components/shadcn-space/tabs/tabs-03.tsx",
        type: "registry:component",
        target: "components/shadcn-space/tabs/tabs-03.tsx",
      },
    ],
    category: categories["tabs"],
  },
  {
    name: "tabs-04",
    title: "Tabs-04 - With Count",
    description: "Tabs component",
    type: "registry:component",
    registryDependencies: ["tabs", "badge"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/tabs/tabs-04.tsx",
        type: "registry:component",
        target: "components/shadcn-space/tabs/tabs-04.tsx",
      },
    ],
    category: categories["tabs"],
  },
  {
    name: "card-01",
    title: "Card-01 - ArticlePreviewCard",
    description: "Card component",
    type: "registry:component",
    registryDependencies: ["card"],
    dependencies: ["motion"],
    files: [
      {
        path: "src/components/shadcn-space/card/card-01.tsx",
        type: "registry:component",
        target: "components/shadcn-space/card/card-01.tsx",
      },
    ],
    category: categories["card"],
  },
  {
    name: "card-02",
    title: "Card-02 - Preview Card",
    description: "Card component",
    type: "registry:component",
    registryDependencies: ["card", "badge"],
    dependencies: ["lucide-react"],
    files: [
      {
        path: "src/components/shadcn-space/card/card-02.tsx",
        type: "registry:component",
        target: "components/shadcn-space/card/card-02.tsx",
      },
    ],
    category: categories["card"],
  },
  {
    name: "card-03",
    title: "Card-03 - Product Card",
    description: "Card component",
    type: "registry:component",
    registryDependencies: ["card", "badge", "progress"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/card/card-03.tsx",
        type: "registry:component",
        target: "components/shadcn-space/card/card-03.tsx",
      },
    ],
    category: categories["card"],
  },
  {
    name: "card-04",
    title: "Card-04 - Welcome Card",
    description: "Card component",
    type: "registry:component",
    registryDependencies: ["card"],
    dependencies: ["lucide-react", "motion"],
    files: [
      {
        path: "src/components/shadcn-space/card/card-04.tsx",
        type: "registry:component",
        target: "components/shadcn-space/card/card-04.tsx",
      },
    ],
    category: categories["card"],
  },
  {
    name: "card-05",
    title: "Card-05 - Analytics Card",
    description: "Card component",
    type: "registry:component",
    registryDependencies: ["card", "badge", "separator"],
    dependencies: [],
    files: [
      {
        path: "src/components/shadcn-space/card/card-05.tsx",
        type: "registry:component",
        target: "components/shadcn-space/card/card-05.tsx",
      },
    ],
    category: categories["card"],
  },
  {
    name: "card-06",
    title: "Card-06 - Statistics Card",
    description: "Card component",
    type: "registry:component",
    registryDependencies: ["card", "badge"],
    dependencies: ["iconify/react"],
    files: [
      {
        path: "src/components/shadcn-space/card/card-06.tsx",
        type: "registry:component",
        target: "components/shadcn-space/card/card-06.tsx",
      },
    ],
    category: categories["card"],
  },
];
